# ----------- CONFIGURABLE START -----------
title:            "LiberXue|FullStack|独立开发者|jekyll blog|GitHub blog"
description:      "Full Stack独立开发者|欢迎来到 LiberXue「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              "/" # 域名
signoff:          "" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: ""
gems: [jekyll-paginate]

# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:title
defaults:
  - values:
      layout: "default"
